### ISSUE TITLE
Fast tokenizer for CaseHOLD

### ISSUE THREAD

**Issue by atreyasha** [reglab/casehold#2]
Hello all,

I am currently using the CaseHOLD dataset downstream as part of the [LexGLUE](https://github.com/coastalcph/lex-glue) benchmarks.

A quick question: it is mentioned that the fast tokenizer for the `case_hold` task is buggy. Since I am testing on a lower-end machine, I tried to stick with the fast tokenizer and observed that the tokenized outputs between it and the legecy tokenizer were the same (at least for the eval and prediction sets).

https://github.com/reglab/casehold/blob/4791f0327afaf17b68e6941f0fff709bed047ff2/multiple_choice/run_multiple_choice.py#L133-L134

Could I ask what the bug is and if it still persists?

**Comment by zlucia** [comment]
Hi, thanks for the question. The fast tokenizer threw an error that causes the tokenizing process to exit, but this may have been resolved in a later version of transformers. If you're not seeing that error and the tokenized outputs are the same for the fast and legacy tokenizer, I think it should be okay to use the fast tokenizer.

**Comment by atreyasha** [comment]
Hi @zlucia, thank you for the prompt response. Closing this issue.
